name: Build and Release Windows Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install g++ (via MSYS2)
        run: |
          choco install mingw
          refreshenv

      - name: Build Windows binary
        run: g++ main.cpp -o RemoveElementsFromFile.exe

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: ./RemoveElementsFromFile.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
